version: '3.1'

services:

  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
#
#  back:
#    build: .
#    container_name: photo-memento-back-test
#    restart: unless-stopped
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
#    ports:
#      - "8091:8080"
#    depends_on:
#      - db